package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Magicking/ether-swarm-services/models"
)

/*CreateGenesisOK Return the address of allocators and private keys if new_allocator
was used.


swagger:response createGenesisOK
*/
type CreateGenesisOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Allocator `json:"body,omitempty"`
}

// NewCreateGenesisOK creates CreateGenesisOK with default headers values
func NewCreateGenesisOK() *CreateGenesisOK {
	return &CreateGenesisOK{}
}

// WithPayload adds the payload to the create genesis o k response
func (o *CreateGenesisOK) WithPayload(payload []*models.Allocator) *CreateGenesisOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create genesis o k response
func (o *CreateGenesisOK) SetPayload(payload []*models.Allocator) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGenesisOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Allocator, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*CreateGenesisDefault Unexpected error.

swagger:response createGenesisDefault
*/
type CreateGenesisDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateGenesisDefault creates CreateGenesisDefault with default headers values
func NewCreateGenesisDefault(code int) *CreateGenesisDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateGenesisDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create genesis default response
func (o *CreateGenesisDefault) WithStatusCode(code int) *CreateGenesisDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create genesis default response
func (o *CreateGenesisDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create genesis default response
func (o *CreateGenesisDefault) WithPayload(payload *models.Error) *CreateGenesisDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create genesis default response
func (o *CreateGenesisDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGenesisDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
