package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Magicking/ether-swarm-services/models"
)

/*GetInformationOK Information of the blockchain.

swagger:response getInformationOK
*/
type GetInformationOK struct {

	// In: body
	Payload *models.Information `json:"body,omitempty"`
}

// NewGetInformationOK creates GetInformationOK with default headers values
func NewGetInformationOK() *GetInformationOK {
	return &GetInformationOK{}
}

// WithPayload adds the payload to the get information o k response
func (o *GetInformationOK) WithPayload(payload *models.Information) *GetInformationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get information o k response
func (o *GetInformationOK) SetPayload(payload *models.Information) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInformationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
