package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
)

// RegisterNodeURL generates an URL for the register node operation
type RegisterNodeURL struct {
	EnodeURL string

	// avoid unkeyed usage
	_ struct{}
}

// Build a url path and query string
func (o *RegisterNodeURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/blockchain/bootnode"

	result.Path = _path

	qs := make(url.Values)

	enodeURL := o.EnodeURL
	if enodeURL != "" {
		qs.Set("enode_url", enodeURL)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *RegisterNodeURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *RegisterNodeURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *RegisterNodeURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on RegisterNodeURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on RegisterNodeURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *RegisterNodeURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
