package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStartNodeParams creates a new StartNodeParams object
// with the default values initialized.
func NewStartNodeParams() StartNodeParams {
	var ()
	return StartNodeParams{}
}

// StartNodeParams contains all the bound params for the start node operation
// typically these are obtained from a http.Request
//
// swagger:parameters startNode
type StartNodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The etherbase to set to the miner.
	  Required: true
	  In: query
	*/
	Etherbase string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *StartNodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEtherbase, qhkEtherbase, _ := qs.GetOK("etherbase")
	if err := o.bindEtherbase(qEtherbase, qhkEtherbase, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StartNodeParams) bindEtherbase(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("etherbase", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("etherbase", "query", raw); err != nil {
		return err
	}

	o.Etherbase = raw

	return nil
}
