package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Information information
// swagger:model Information
type Information struct {

	// bootnodes urls
	BootnodesUrls []interface{} `json:"bootnodes_urls"`

	// genesis
	Genesis *Genesis `json:"genesis,omitempty"`

	// networkid
	Networkid int64 `json:"networkid,omitempty"`
}

// Validate validates this information
func (m *Information) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGenesis(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Information) validateGenesis(formats strfmt.Registry) error {

	if swag.IsZero(m.Genesis) { // not required
		return nil
	}

	if m.Genesis != nil {

		if err := m.Genesis.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
